### ISSUE TITLE
Changing the logic of obtaining EUR equivalent in XOR

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card-ios#6]
See details in soramitsu/sora-card-backend#147

**Comment by Tieumsan** [comment]
@2bogd can we assess the impact of this technical debt ?

This is to enable us to categorise it and prioritise it in a rational way.

- [ ] **Technical impact**

- What are the risks and consequences of leaving this technical debt unaddressed ?
- What do we gain from paying off this debt ?

- [ ] **Business impact**

I can take it further once we’ve established the technical impact and risks associated with this debt.

- What are the business impact and risks associated with this debt (impact on UX, security, …)

_______

We should try to integrate this practice as part of our processes to be sure that we retain control over our codebase and technical debt. Every software has technical debt, but we should make sure that it’s explicit (we are aware of it), so that we can better control it.


cc. @bgodlin taking into account that we want to add a feature that might impact this one: choosing the fiat currency of reference in the wallet (users should be able to see the value of their crypto in their preferred fiat currency)
